-- DROP DATABASE IF Exists `urls`;
-- CREATE DATABASE `urls`;

DROP TABLE IF EXISTS `Urls`;
CREATE TABLE IF NOT EXISTS `Urls` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `url` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;